{"items": [
  { id: "attendee", label: "Attendee", url: "#"},
  { id: "tutor", label: "Tutor", url: "#"},
  { id: "teacher": label: "Teacher", url: "#"},
  { id: "wealth", label: "Wealth", url: "#"},
  { id: "person", label: "Person", url: "#"},
  { id: "relative", label: "Relative", url: "#"},
  { id: "parent", label: "Parent", url: "#"},
  { id: "child": label: "Child", url: "#"}, 
  { id: "friend", label: "Friend", url: "#"},
  { id: "spouse", label: "Spouse", url: "#"},
  { id: "utility", label: "Utility", url: "#" },
  { id: "process", label: "Process", url: "#" },
  { id: "application", label: "Applications", url: "#"},
  { id: "tool", label: "Tool", url: "#" },
  { id: "stock", label: "Stock", url: "#" },
  { id: "option", label: "Option", url: "#" },
  { id: "quote", label: "Quote", url: "#" },
  { id: "account", label: "Account", url: "#" },
  { id: "database", label: "Database", url: "#" },
  { id: "browser", label: "Browser", url: "#"},
  { id: "cookie", label: "Cookie", url: "#"},
  { id: "site", label: "Site", url: "#"},
  { id: "datasource", label: "Datasource", url: "#"},
  { id: "object", label: "Object", url: "#" },
  { id: "predicate", label: "Predicate", url: "#" },
  { id: "celebrity", label: "Celebrity", url: "#"},
  { id: "user", label: "User", url: "#"}
 ]
}