#!/bin/sh -x
JSDOCTOOLKITDIR="src/Contrib/jsdoc-toolkit-trunk"
JSDOC="java -Djsdoc.dir=${JSDOCTOOLKITDIR}/jsdoc-toolkit -Djsdoc.template.dir=${JSDOCTOOLKITDIR}/jsdoc-toolkit/templates"
${JSDOC} -jar ${JSDOCTOOLKITDIR}/jsdoc-toolkit/jsrun.jar ${JSDOCTOOLKITDIR}/jsdoc-toolkit/app/run.js \
-r=5 -d=src/mashups/site/docs \
-t=${JSDOCTOOLKITDIR}/jsdoc-toolkit/templates/jsdoc \
src/Learn \
src/mashups/scripts \
src/mashups/api \
src/tabulator \
src/ajax \
src/webapp/api \
src/webapp/extensions
